#!/usr/bin/env python3
"""
Export curation flags from Supabase to markdown files.

This script queries Supabase for workdesk summaries with flags set,
and generates curated source lists for the journal assembly process.

Usage:
    uv run scripts/export_curation_flags.py
"""

import os
import sys
from pathlib import Path
from typing import List, Dict, Any
from dotenv import load_dotenv
from supabase import create_client, Client

# Load environment variables
load_dotenv(Path(__file__).parent / ".env")

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_KEY")

if not SUPABASE_URL or not SUPABASE_KEY:
    print("Error: SUPABASE_URL and SUPABASE_SERVICE_KEY must be set in scripts/.env")
    print("See scripts/.env.example for configuration")
    sys.exit(1)

# Initialize Supabase client
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# Paths
WORKDESK_DIR = Path(__file__).parent.parent / "workdesk"
CURATED_ANNEX_FILE = WORKDESK_DIR / "curated_annex_journal_sources.md"
OMITTED_FILE = WORKDESK_DIR / "omitted_sources.md"


def fetch_workdesk_metadata() -> List[Dict[str, Any]]:
    """Fetch all workdesk summary metadata from Supabase."""
    response = supabase.table("summary_metadata").select("*").is_("journal_date", "null").execute()
    return response.data


def export_annex_sources(metadata: List[Dict[str, Any]]) -> None:
    """Export summaries with annex_flag=true to curated annex sources file."""
    annex_summaries = [m for m in metadata if m.get("annex_flag")]

    if not annex_summaries:
        print("No summaries flagged for annex journal")
        return

    # Sort by summary_id
    annex_summaries.sort(key=lambda x: x.get("summary_id", ""))

    with open(CURATED_ANNEX_FILE, "w", encoding="utf-8") as f:
        f.write("# Curated Annex Journal Sources\n\n")
        f.write(f"<!-- Auto-generated by export_curation_flags.py -->\n")
        f.write(f"<!-- Total: {len(annex_summaries)} summaries -->\n\n")

        for summary in annex_summaries:
            url = summary.get("url", "")
            summary_id = summary.get("summary_id", "")
            standout = summary.get("standout_flag", False)
            upvote = summary.get("upvote_flag", False)
            downvote = summary.get("downvote_flag", False)

            # Add checkbox (checked)
            f.write(f"- [x] {summary_id}. {url}")

            # Add markers
            if standout:
                f.write(" ⭐")
            if upvote:
                f.write(" 👍")
            if downvote:
                f.write(" 👎")

            f.write("\n\n")

    print(f"✓ Exported {len(annex_summaries)} annex sources to {CURATED_ANNEX_FILE}")


def export_omitted_sources(metadata: List[Dict[str, Any]]) -> None:
    """Export summaries with omit_flag=true to omitted sources file."""
    omitted_summaries = [m for m in metadata if m.get("omit_flag")]

    if not omitted_summaries:
        print("No summaries flagged for omission")
        return

    # Sort by summary_id
    omitted_summaries.sort(key=lambda x: x.get("summary_id", ""))

    with open(OMITTED_FILE, "w", encoding="utf-8") as f:
        f.write("# Omitted Sources\n\n")
        f.write(f"<!-- Auto-generated by export_curation_flags.py -->\n")
        f.write(f"<!-- Total: {len(omitted_summaries)} summaries -->\n\n")

        for summary in omitted_summaries:
            url = summary.get("url", "")
            summary_id = summary.get("summary_id", "")
            upvote = summary.get("upvote_flag", False)
            downvote = summary.get("downvote_flag", False)

            f.write(f"- [ ] {summary_id}. {url}")

            # Add vote markers if present
            if upvote:
                f.write(" 👍")
            if downvote:
                f.write(" 👎")

            f.write("\n\n")

    print(f"✓ Exported {len(omitted_summaries)} omitted sources to {OMITTED_FILE}")


def main():
    """Main execution function."""
    print("Fetching workdesk metadata from Supabase...")

    try:
        metadata = fetch_workdesk_metadata()
        print(f"Found {len(metadata)} workdesk summaries with metadata")

        # Export annex sources
        export_annex_sources(metadata)

        # Export omitted sources
        export_omitted_sources(metadata)

        print("\n✅ Export complete!")
        print(f"   - Annex sources: {CURATED_ANNEX_FILE}")
        print(f"   - Omitted sources: {OMITTED_FILE}")

    except Exception as e:
        print(f"❌ Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
