#!/usr/bin/env python3
"""
Convert markdown summary to JSON v1.0 format.

This script parses a markdown summary generated by summarize.prompt
and converts it to the structured JSON v1.0 format.
"""

import re
import json
import sys
from datetime import datetime, timezone
from typing import Dict, Any, Optional

def parse_markdown_summary(markdown_text: str, url: str) -> Dict[str, Any]:
    """Parse markdown summary and convert to JSON v1.0 format."""

    lines = markdown_text.strip().split('\n')

    # Extract title (first line, after ##)
    title_match = re.match(r'##\s+(.+)', lines[0])
    title = title_match.group(1).strip() if title_match else "Untitled"

    # Extract URL (second non-empty line)
    url_from_content = None
    for line in lines[1:5]:
        if line.strip().startswith('http'):
            url_from_content = line.strip()
            break

    # Extract original title
    original_title = None
    original_title_match = re.search(r'\*\*Original Title\*\*:\s*(.+)', markdown_text)
    if original_title_match:
        original_title = original_title_match.group(1).strip()

    # Extract one-sentence summary (paragraph after URL, before Content Type)
    one_sentence = ""
    in_intro = False
    for i, line in enumerate(lines):
        if line.strip().startswith('http'):
            in_intro = True
            continue
        if in_intro and line.strip() and not line.startswith('**'):
            one_sentence = line.strip()
            break

    # Extract language
    language_match = re.search(r'\*\*Language\*\*:\s*(\w+)', markdown_text)
    language = language_match.group(1) if language_match else "ja"

    # Extract content type
    content_type_match = re.search(r'\*\*Content Type\*\*:\s*(.+)', markdown_text)
    content_type = content_type_match.group(1).strip() if content_type_match else "📊 Industry News (業界ニュース)"

    # Extract scores
    scores_match = re.search(
        r'\*\*Scores\*\*:\s*Signal:(\d+)/5\s*\|\s*Depth:(\d+)/5\s*\|\s*Unique:(\d+)/5\s*\|\s*Practical:(\d+)/5\s*\|\s*Anti-Hype:(\d+)/5',
        markdown_text
    )

    journal_scores_match = re.search(
        r'\*\*Main Journal\*\*:\s*(\d+)/100\s*\|\s*\*\*Annex Potential\*\*:\s*(\d+)/100\s*\|\s*\*\*Overall\*\*:\s*(\d+)/100',
        markdown_text
    )

    scores = {
        "signal": int(scores_match.group(1)) if scores_match else 3,
        "depth": int(scores_match.group(2)) if scores_match else 3,
        "uniqueness": int(scores_match.group(3)) if scores_match else 3,
        "practical": int(scores_match.group(4)) if scores_match else 3,
        "antiHype": int(scores_match.group(5)) if scores_match else 3,
        "mainJournal": int(journal_scores_match.group(1)) if journal_scores_match else 50,
        "annexPotential": int(journal_scores_match.group(2)) if journal_scores_match else 50,
        "overall": int(journal_scores_match.group(3)) if journal_scores_match else 50
    }

    # Extract topics
    topics_match = re.search(r'\*\*Topics\*\*:\s*\[\[(.+?)\]\]', markdown_text)
    topics = []
    if topics_match:
        topics_str = topics_match.group(1)
        topics = [t.strip() for t in topics_str.split(',')]

    # Extract summary body (everything after Topics line)
    summary_body = ""
    topics_line_found = False
    for line in lines:
        if '**Topics**:' in line:
            topics_line_found = True
            continue
        if topics_line_found and line.strip():
            summary_body += line + "\n"

    summary_body = summary_body.strip()

    # Build JSON structure
    json_data = {
        "metadata": {
            "version": "1.0",
            "generatedAt": datetime.now(timezone.utc).isoformat(),
            "generatedBy": "gemini-3-flash-preview"
        },
        "content": {
            "title": title,
            "originalTitle": original_title,
            "url": url_from_content or url,
            "language": language,
            "contentType": content_type,
            "oneSentenceSummary": one_sentence,
            "summaryBody": summary_body,
            "topics": topics,
            "scores": scores
        }
    }

    return json_data

def main():
    import argparse

    parser = argparse.ArgumentParser(description='Convert markdown summary to JSON v1.0')
    parser.add_argument('input', help='Input markdown file')
    parser.add_argument('--output', '-o', help='Output JSON file (default: stdout)')
    parser.add_argument('--url', help='URL of the article (if not in markdown)')

    args = parser.parse_args()

    # Read markdown
    with open(args.input, 'r', encoding='utf-8') as f:
        markdown_text = f.read()

    # Parse and convert
    json_data = parse_markdown_summary(markdown_text, args.url or "")

    # Output
    json_output = json.dumps(json_data, ensure_ascii=False, indent=2)

    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(json_output)
        print(f"Converted to JSON: {args.output}", file=sys.stderr)
    else:
        print(json_output)

if __name__ == '__main__':
    main()
