#!/usr/bin/env python3
"""STEP_13/14 — tag, clean up the branch, and draft the GitHub release.

A live run (after the PR is merged): fast-forwards local main, **verifies the
cycle actually landed on main** (``journals/<date>/journal-metadata.json`` must
exist there — otherwise it aborts before tagging or deleting anything), creates
the annotated ``<date>`` tag, pushes it, deletes the feature branch, and creates
a **draft** release from the standard two-section template (computing the
Japanese 曜日), then checks the six published links resolve.

    --dry-run  print the tag, the full release body, and the six URLs; mutate
               nothing (this is the eval path).
    live run   prompts before tagging/pushing/releasing unless --yes.

Usage:
    uv run scripts/release_journal.py 2026-08-22 --dry-run
    uv run scripts/release_journal.py 2026-08-22            # live
    uv run scripts/release_journal.py 2026-08-22 --branch journal/2026-08-22
"""

import datetime
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from workflow import git_gh  # noqa: E402
from workflow.journal_paths import Paths  # noqa: E402

_WEEKDAYS = "月火水木金土日"  # Python weekday(): Mon=0 .. Sun=6


def jp_weekday(date):
    return _WEEKDAYS[datetime.date.fromisoformat(date).weekday()] + "曜日"


def jp_date(date, with_weekday=False):
    y, m, d = date.split("-")
    wd = jp_weekday(date) if with_weekday else ""
    return f"{y}年{m}月{d}日{wd}号"


def release_links(date):
    """The six links a release lists: 3 Pages + 3 blob@tag."""
    p = Paths(date)
    return p.pages_links + p.blob_links


def build_release_body(date):
    p = Paths(date)
    us = p.us
    pages_main, pages_annex, pages_summaries = p.pages_links
    blob_weekly, blob_annex, blob_omitted = p.blob_links
    return (
        "# Website\n\n"
        f"- [GenAI週刊 {jp_date(date)} - GenAI週刊]({pages_main})\n"
        f"- [GenAI週刊 Annex {jp_date(date)} - GenAI週刊]({pages_annex})\n"
        f"- [{jp_date(date, with_weekday=True)} サマリー一覧 - GenAI週刊]({pages_summaries})\n\n"
        "# Generated by Claude\n\n"
        f"- [00_weekly_journal_{us}.md]({blob_weekly})\n"
        f"- [01_annex_journal_{us}.md]({blob_annex})\n"
        f"- [02_omitted_summaries.md]({blob_omitted})\n"
    )


def landed_on_main(date):
    """True if the archived cycle exists in the checked-out main tree."""
    return Paths(date).metadata.exists()


def _verify_links(links):
    from verify_journal import _check_url
    ok = True
    for url in links:
        status = _check_url(url)
        mark = "✅" if 200 <= status < 400 else "❌"
        if not (200 <= status < 400):
            ok = False
        print(f"  {mark} {status or 'conn-error'}  {url}")
    return ok


def release(date, dry_run=False, assume_yes=False, branch=None, verify_links=False):
    branch = branch or f"journal/{date}"
    body = build_release_body(date)
    links = release_links(date)

    if dry_run:
        print(f"tag: {date}   (annotated)")
        print(f"feature branch to delete: {branch}")
        print("release title: " + date + "  (draft)")
        print("--- release body ---")
        print(body, end="")
        print("--- 6 links ---")
        for u in links:
            print(f"  {u}")
        print("[dry-run] no tag, push, branch delete, or release created.")
        return body

    # live
    if not assume_yes:
        ans = input(f"Live release {date}: tag, push, delete {branch}, draft "
                    f"release? (yes/no): ")
        if ans.lower() not in ("yes", "y"):
            print("Cancelled.")
            return body

    # 1. fast-forward main
    git_gh.run(["git", "checkout", "main"])
    git_gh.run(["git", "-c", f"credential.helper={git_gh.CRED_HELPER}",
                "pull", "--ff-only", git_gh.REMOTE_URL, "main"])

    # 1b. guard: the cycle must be on main before we tag it or delete the
    #     feature branch. An unmerged PR would otherwise be tagged as a stale
    #     main and lose its branch (ff-only "succeeds" on an unchanged main).
    if not landed_on_main(date):
        raise SystemExit(
            f"❌ journals/{date}/journal-metadata.json is not on main after "
            f"fast-forward — is PR for {branch} merged? Aborting before tag / "
            f"branch delete / release.")

    # 2. annotated tag (idempotent) + push
    existing = git_gh._exec(["git", "tag", "-l", date], capture=True).stdout.strip()
    if existing == date:
        print(f"tag {date} already exists — skipping tag create.")
    else:
        git_gh.run(["git", "tag", "-a", date, "-m", f"Weekly GenAI Journal {date}"])
    git_gh.push(date)

    # 3. delete feature branch (best-effort, local + remote)
    git_gh.run(["git", "branch", "-D", branch], check=False)
    git_gh.run(["git", "-c", f"credential.helper={git_gh.CRED_HELPER}",
                "push", git_gh.REMOTE_URL, "--delete", branch], check=False)

    # 4. draft release (idempotent)
    import tempfile
    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False,
                                     encoding="utf-8") as fh:
        fh.write(body)
        notes = fh.name
    rel = git_gh.run(["gh", "release", "create", date, "--title", date,
                      "--notes-file", notes, "--draft"], check=False)

    # 5. verify links
    if verify_links:
        print("Verifying published links:")
        _verify_links(links)

    if rel.returncode == 0:
        print(f"✅ draft release {date} created — human publishes it after review.")
    else:
        print(f"⚠️  gh release create exited {rel.returncode} (already exists?) — "
              f"check `gh release view {date}` before publishing.")
    return body


def main():
    args = sys.argv[1:]
    dry_run = "--dry-run" in args
    assume_yes = ("--yes" in args) or ("-y" in args)
    verify_links = "--verify-links" in args
    branch = None
    if "--branch" in args:
        i = args.index("--branch")
        branch = args[i + 1]
        del args[i:i + 2]
    positional = [a for a in args if not a.startswith("-")]
    if len(positional) != 1:
        print("Usage: uv run scripts/release_journal.py <YYYY-MM-DD> "
              "[--dry-run] [--yes] [--branch NAME] [--verify-links]")
        sys.exit(1)

    release(positional[0], dry_run=dry_run, assume_yes=assume_yes,
            branch=branch, verify_links=verify_links)


if __name__ == "__main__":
    main()
