#!/usr/bin/env python3
"""Tests for release_journal.py (STEP_13/14).

Exercises the release-body builder (exact 2-section template, Japanese 曜日),
the six links, and that --dry-run makes zero real git/gh calls (git_gh._exec
monkeypatched with a recorder).

Run:
    uv run scripts/test_release_journal.py
"""

import io
import os
import sys
import unittest
from contextlib import redirect_stdout

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import release_journal as R  # noqa: E402
from workflow import git_gh  # noqa: E402


class TestBody(unittest.TestCase):
    def test_weekday(self):
        self.assertEqual(R.jp_weekday("2026-08-22"), "土曜日")  # Saturday
        self.assertEqual(R.jp_weekday("2025-12-27"), "土曜日")

    def test_body_structure(self):
        body = R.build_release_body("2026-08-22")
        self.assertIn("# Website", body)
        self.assertIn("# Generated by Claude", body)
        self.assertIn("2026年08月22日土曜日号 サマリー一覧", body)
        self.assertIn("GenAI週刊 2026年08月22日号 - GenAI週刊", body)
        self.assertIn("GenAI週刊 Annex 2026年08月22日号", body)
        # exactly the six links
        self.assertEqual(body.count("https://"), 6)

    def test_six_links(self):
        links = R.release_links("2026-08-22")
        self.assertEqual(len(links), 6)
        self.assertEqual(sum(1 for u in links if "github.io" in u), 3)
        self.assertEqual(sum(1 for u in links
                             if "github.com" in u and "/blob/2026-08-22/" in u), 3)
        self.assertTrue(links[3].endswith("00_weekly_journal_2026_08_22.md"))


class TestDryRun(unittest.TestCase):
    def setUp(self):
        self._real = git_gh._exec
        self.calls = []
        git_gh._exec = lambda argv, **k: self.calls.append(list(argv))

    def tearDown(self):
        git_gh._exec = self._real

    def test_dry_run_zero_calls(self):
        buf = io.StringIO()
        with redirect_stdout(buf):
            R.release("2026-08-22", dry_run=True)
        out = buf.getvalue()
        self.assertEqual(self.calls, [])
        self.assertIn("tag: 2026-08-22", out)
        self.assertIn("# Website", out)
        self.assertIn("2026年08月22日土曜日号", out)
        # all six URLs listed
        self.assertEqual(out.count("https://beijaflor.github.io"), 3 + 3)  # body + list
        self.assertIn("[dry-run] no tag", out)


class TestMergeGuard(unittest.TestCase):
    """Live path must abort before tag/branch-delete when the cycle is not on main."""

    def setUp(self):
        self._real = git_gh._exec
        self.calls = []
        # every git/gh call is recorded (and "succeeds") — nothing real runs
        git_gh._exec = lambda argv, **k: (self.calls.append(list(argv))
                                          or type("R", (), {"returncode": 0,
                                                            "stdout": ""})())

    def tearDown(self):
        git_gh._exec = self._real

    def test_unmerged_cycle_aborts_before_tag_and_delete(self):
        buf = io.StringIO()
        with redirect_stdout(buf), self.assertRaises(SystemExit):
            R.release("2099-12-31", assume_yes=True)  # no journals/2099-12-31 on main
        flat = [" ".join(c) for c in self.calls]
        self.assertTrue(any("checkout main" in c for c in flat))
        self.assertFalse(any("tag -a" in c for c in flat))
        self.assertFalse(any("--delete" in c or "branch -D" in c for c in flat))
        self.assertFalse(any("release create" in c for c in flat))

    def test_landed_on_main_true_for_archived_cycle(self):
        self.assertTrue(R.landed_on_main("2026-08-22"))
        self.assertFalse(R.landed_on_main("2099-12-31"))


if __name__ == "__main__":
    unittest.main(verbosity=2)
