name: Continuous Integration

on:
  push:
    branches: ['**']  # Run on any branch
    paths:
      - 'website/**'
  pull_request:
    branches: ['**']  # Run on PRs to any branch
    paths:
      - 'website/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'website/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./website

      - name: Run type check
        run: npm run type-check
        working-directory: ./website

      - name: Run linting
        run: npm run lint
        working-directory: ./website

      - name: Test build
        run: npm run build
        working-directory: ./website
        env:
          ASTRO_BASE: /gen-ai-journal-dev/

  deploy-preview:
    runs-on: ubuntu-latest
    needs: test
    # Deploy from any branch for preview (not just main)
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'website/package-lock.json'

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci
        working-directory: ./website

      - name: Build site
        run: npm run build
        working-directory: ./website
        env:
          ASTRO_BASE: ${{ steps.pages.outputs.base_path }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './website/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4